const express = require('express');
const router = express.Router();
const bcrypt = require('bcryptjs');
const { body, validationResult } = require('express-validator');
const { pool, isPostgres, dbPlaceholder, dbPlaceholders, addParam } = require('../config/database');
const { authenticate, authorize } = require('../middleware/auth');
const {
  isSuperAdmin,
  isAdminRole,
  denyAccess,
  appendSekolahScope,
  resolveTargetSekolahId,
  sameSekolah,
  normalizeKelas
} = require('../utils/accessControl');
const multer = require('multer');
const path = require('path');
const fs = require('fs'); // Tambahan untuk hapus file lama
const { getUploadDir, resolveExistingPublicUploadPath } = require('../utils/uploadPaths');

const LIKE_OPERATOR = isPostgres ? 'ILIKE' : 'LIKE';
const COUNT_TOTAL_SQL = isPostgres ? 'COUNT(*)::int' : 'COUNT(*)';

function isValidEmail(value) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(value || '').trim());
}

async function getUserForAccess(id) {
  const result = await pool.execute(
    `SELECT id, id_sekolah, peran, foto, nis, email FROM users WHERE id = ${dbPlaceholder(1)}`,
    [id]
  );

  return result.rows[0] || null;
}

function canAccessUserTarget(currentUser, targetUser, allowSelf = true) {
  if (!targetUser) return false;
  if (isSuperAdmin(currentUser)) return true;
  if (allowSelf && Number(currentUser.id) === Number(targetUser.id)) return true;

  return isAdminRole(currentUser.peran) && sameSekolah(currentUser, targetUser.id_sekolah);
}

async function ensurePasswordResetRequestsTable() {
  if (isPostgres) {
    await pool.execute(
      `CREATE TABLE IF NOT EXISTS password_reset_requests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NULL,
        identifier VARCHAR(191) NOT NULL,
        peran VARCHAR(50) NULL,
        id_sekolah BIGINT NULL,
        status VARCHAR(30) NOT NULL DEFAULT 'pending',
        ip_address VARCHAR(80) NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        resolved_at TIMESTAMP NULL
      )`
    );
    await pool.execute('CREATE INDEX IF NOT EXISTS idx_password_reset_user_status ON password_reset_requests (user_id, status)');
    await pool.execute('CREATE INDEX IF NOT EXISTS idx_password_reset_school_status ON password_reset_requests (id_sekolah, status)');
    await pool.execute('CREATE INDEX IF NOT EXISTS idx_password_reset_created ON password_reset_requests (created_at)');
    return;
  }

  await pool.execute(
    `CREATE TABLE IF NOT EXISTS password_reset_requests (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      user_id BIGINT UNSIGNED NULL,
      identifier VARCHAR(191) NOT NULL,
      peran VARCHAR(50) NULL,
      id_sekolah BIGINT UNSIGNED NULL,
      status VARCHAR(30) NOT NULL DEFAULT 'pending',
      ip_address VARCHAR(80) NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      resolved_at DATETIME NULL,
      PRIMARY KEY (id),
      KEY idx_password_reset_user_status (user_id, status),
      KEY idx_password_reset_school_status (id_sekolah, status),
      KEY idx_password_reset_created (created_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`
  );
}

// ============================================================
// GET /api/users — daftar pengguna (admin only)
// ============================================================
router.get('/', authenticate, authorize('admin'), async (req, res) => {
  try {
    const { peran, search, id_sekolah } = req.query;
    const parsedPage = Number.parseInt(req.query.page, 10);
    const parsedLimit = Number.parseInt(req.query.limit, 10);
    const page = Number.isInteger(parsedPage) && parsedPage > 0 ? parsedPage : 1;
    const limit = Math.min(
      100,
      Math.max(1, Number.isInteger(parsedLimit) && parsedLimit > 0 ? parsedLimit : 20)
    );
    const offset = (page - 1) * limit;
    let where = [];
    let params = [];

    if (peran) {
      where.push(`u.peran = ${addParam(params, peran === 'admin' ? 'admin_sekolah' : peran)}`);
    }
    if (search) {
      const searchTerm = '%' + search + '%';
      where.push(
        `(u.nama ${LIKE_OPERATOR} ${addParam(params, searchTerm)} OR ` +
        `u.email ${LIKE_OPERATOR} ${addParam(params, searchTerm)} OR ` +
        `u.nis ${LIKE_OPERATOR} ${addParam(params, searchTerm)})`
      );
    }

    const scope = appendSekolahScope(where, params, req.user, 'u.id_sekolah', id_sekolah);
    if (!scope.ok) return denyAccess(res);

    const whereStr = where.length > 0 ? 'WHERE ' + where.join(' AND ') : '';

    const usersResult = await pool.query(
      `SELECT u.id, u.nama, u.email, u.peran, u.id_sekolah, s.nama_sekolah,
              u.mata_pelajaran, u.nip, u.kelas, u.nis, u.foto, u.is_aktif, u.created_at
       FROM users u
       LEFT JOIN sekolah s ON s.id = u.id_sekolah
       ${whereStr}
       ORDER BY u.peran, u.nama
       LIMIT ${limit} OFFSET ${offset}`,
      params
    );
    const rows = usersResult.rows;

    const totalResult = await pool.query(
      `SELECT ${COUNT_TOTAL_SQL} as total
       FROM users u
       LEFT JOIN sekolah s ON s.id = u.id_sekolah
       ${whereStr}`,
      params
    );
    const total = totalResult.rows;

    return res.json({
      success: true,
      data: rows,
      pagination: { total: total[0].total, page, limit }
    });
  } catch (err) {
    return res.status(500).json({ success: false, message: 'Terjadi kesalahan server.' });
  }
});

// ============================================================
// GET /api/users/password-reset-requests — permintaan reset password
// ============================================================
router.get('/password-reset-requests', authenticate, authorize('admin'), async (req, res) => {
  try {
    await ensurePasswordResetRequestsTable();

    const limit = Math.min(parseInt(req.query.limit, 10) || 20, 100);
    const params = [];
    const where = [`pr.status = ${addParam(params, 'pending')}`];

    const scope = appendSekolahScope(where, params, req.user, 'pr.id_sekolah', req.query.id_sekolah);
    if (!scope.ok) return denyAccess(res);

    const result = await pool.query(
      `SELECT
         pr.id,
         pr.user_id,
         pr.identifier,
         pr.peran,
         pr.id_sekolah,
         pr.status,
         pr.created_at,
         u.nama,
         u.email,
         u.nis,
         u.kelas,
         u.mata_pelajaran,
         s.nama_sekolah
       FROM password_reset_requests pr
       LEFT JOIN users u ON u.id = pr.user_id
       LEFT JOIN sekolah s ON s.id = pr.id_sekolah
       WHERE ${where.join(' AND ')}
       ORDER BY pr.created_at DESC
       LIMIT ${limit}`,
      params
    );

    return res.json({ success: true, data: result.rows });
  } catch (err) {
    console.error('Password reset request list error:', err.message);
    return res.status(500).json({ success: false, message: 'Gagal mengambil permintaan reset password.' });
  }
});

// ============================================================
// PATCH /api/users/password-reset-requests/:id/resolve
// ============================================================
router.patch('/password-reset-requests/:id/resolve', authenticate, authorize('admin'), async (req, res) => {
  try {
    await ensurePasswordResetRequestsTable();

    const result = await pool.execute(
      `SELECT id, id_sekolah FROM password_reset_requests WHERE id = ${dbPlaceholder(1)}`,
      [req.params.id]
    );
    const rows = result.rows;

    if (rows.length === 0) {
      return res.status(404).json({ success: false, message: 'Permintaan reset password tidak ditemukan.' });
    }

    if (!isSuperAdmin(req.user) && !sameSekolah(req.user, rows[0].id_sekolah)) {
      return denyAccess(res);
    }

    await pool.execute(
      `UPDATE password_reset_requests SET status = 'resolved', resolved_at = NOW() WHERE id = ${dbPlaceholder(1)}`,
      [req.params.id]
    );

    return res.json({ success: true, message: 'Permintaan reset password ditandai selesai.' });
  } catch (err) {
    console.error('Password reset request resolve error:', err.message);
    return res.status(500).json({ success: false, message: 'Gagal memperbarui permintaan reset password.' });
  }
});

// ============================================================
// GET /api/users/:id
// ============================================================
router.get('/:id', authenticate, async (req, res) => {
  // Hanya admin atau pemilik akun sendiri
  try {
    const result = await pool.execute(
      `SELECT u.id, u.nama, u.email, u.peran, u.id_sekolah, s.nama_sekolah,
              u.mata_pelajaran, u.nip, u.kelas, u.nis, u.foto, u.is_aktif, u.created_at
       FROM users u
       LEFT JOIN sekolah s ON s.id = u.id_sekolah
       WHERE u.id = ${dbPlaceholder(1)}`,
      [req.params.id]
    );
    const rows = result.rows;
    if (rows.length === 0) return res.status(404).json({ success: false, message: 'Pengguna tidak ditemukan.' });
    if (!canAccessUserTarget(req.user, rows[0], true)) return denyAccess(res);
    return res.json({ success: true, data: rows[0] });
  } catch (err) {
    return res.status(500).json({ success: false, message: 'Terjadi kesalahan server.' });
  }
});

// ============================================================
// POST /api/users — tambah pengguna (admin)
// ============================================================
router.post('/', authenticate, authorize('admin'), [
  body('nama').trim().notEmpty().withMessage('Nama wajib diisi'),
  body('email')
    .custom((value, { req }) => {
      const peran = req.body.peran === 'admin' ? 'admin_sekolah' : req.body.peran;
      const email = String(value || '').trim();

      if (peran === 'guru' && !isValidEmail(email)) {
        throw new Error('Email guru wajib diisi dengan format yang valid.');
      }

      return true;
    }),
  body('nis')
    .if((value, { req }) => req.body.peran === 'siswa')
    .trim()
    .notEmpty()
    .withMessage('NIS siswa wajib diisi'),
  body('password').isLength({ min: 6 }).withMessage('Password minimal 6 karakter'),
  body('peran').isIn(['admin', 'admin_sekolah', 'guru', 'siswa']).withMessage('Peran tidak valid'),
], async (req, res) => {
  const errors = validationResult(req);
  if (!errors.isEmpty()) return res.status(400).json({ success: false, errors: errors.array() });

  const { nama, email, password, peran, mata_pelajaran, nip, kelas, nis, id_sekolah } = req.body;
  const normalizedPeran = peran === 'admin' ? 'admin_sekolah' : peran;
  const normalizedEmail = normalizedPeran === 'siswa'
    ? null
    : (String(email || '').trim().toLowerCase() || null);
  const normalizedNis = normalizedPeran === 'siswa' ? String(nis).trim() : null;
  const normalizedSiswaKelas = normalizedPeran === 'siswa' ? normalizeKelas(kelas) : null;
  const targetSekolah = resolveTargetSekolahId(req.user, id_sekolah);

  if (!targetSekolah.ok) {
    return denyAccess(res);
  }

  try {
    if (normalizedEmail) {
      const existingResult = await pool.execute(
        `SELECT id FROM users WHERE LOWER(email) = ${dbPlaceholder(1)}`,
        [normalizedEmail]
      );
      const existing = existingResult.rows;
      if (existing.length > 0) return res.status(409).json({ success: false, message: 'Email sudah terdaftar.' });
    }

    if (normalizedPeran === 'siswa') {
      const existingNisResult = await pool.execute(
        `SELECT id FROM users WHERE nis = ${dbPlaceholder(1)} AND peran = 'siswa'`,
        [normalizedNis]
      );
      const existingNis = existingNisResult.rows;
      if (existingNis.length > 0) return res.status(409).json({ success: false, message: 'NIS sudah terdaftar.' });
    }

    const hashed = await bcrypt.hash(password, 10);
    const result = await pool.execute(
      `INSERT INTO users (nama, email, password, peran, mata_pelajaran, nip, kelas, nis, id_sekolah)
       VALUES (${dbPlaceholders(9).join(', ')})${isPostgres ? ' RETURNING id' : ''}`,
      [
        nama,
        normalizedEmail,
        hashed,
        normalizedPeran,
        normalizedPeran === 'guru' ? mata_pelajaran || null : null,
        normalizedPeran === 'guru' ? nip || null : null,
        normalizedSiswaKelas || null,
        normalizedNis,
        targetSekolah.id_sekolah
      ]
    );

    return res.status(201).json({
      success: true,
      message: 'Pengguna berhasil ditambahkan.',
      data: { id: isPostgres ? result.rows[0].id : result.insertId }
    });
  } catch (err) {
    return res.status(500).json({ success: false, message: 'Terjadi kesalahan server.' });
  }
});

// ============================================================
// PUT /api/users/:id — update pengguna
// ============================================================
router.put('/:id', authenticate, async (req, res) => {
  const { nama, email, mata_pelajaran, nip, kelas, nis } = req.body;

  try {
    const targetUser = await getUserForAccess(req.params.id);
    if (!targetUser) return res.status(404).json({ success: false, message: 'Pengguna tidak ditemukan.' });
    if (!canAccessUserTarget(req.user, targetUser, true)) return denyAccess(res);
    if (!String(nama || '').trim()) {
      return res.status(400).json({ success: false, message: 'Nama wajib diisi.' });
    }

    const normalizedUserKelas =
      kelas !== undefined && kelas !== null && String(kelas).trim() !== ''
        ? normalizeKelas(kelas)
        : null;
    let finalNis = null;
    let finalEmail = targetUser.email || null;

    if (targetUser.peran === 'guru') {
      const requestedEmail = email !== undefined
        ? String(email || '').trim().toLowerCase()
        : String(targetUser.email || '').trim().toLowerCase();

      if (!isValidEmail(requestedEmail)) {
        return res.status(400).json({
          success: false,
          message: 'Email guru wajib diisi dengan format yang valid.'
        });
      }

      const existingEmailResult = await pool.execute(
        `SELECT id FROM users WHERE LOWER(email) = ${dbPlaceholder(1)} AND id <> ${dbPlaceholder(2)}`,
        [requestedEmail, req.params.id]
      );
      const existingEmail = existingEmailResult.rows;

      if (existingEmail.length > 0) {
        return res.status(409).json({
          success: false,
          message: 'Email sudah terdaftar.'
        });
      }

      finalEmail = requestedEmail;
    } else if (['admin', 'admin_sekolah'].includes(targetUser.peran) && email !== undefined) {
      const requestedEmail = String(email || '').trim().toLowerCase();
      finalEmail = requestedEmail || null;

      if (finalEmail) {
        const existingEmailResult = await pool.execute(
          `SELECT id FROM users WHERE LOWER(email) = ${dbPlaceholder(1)} AND id <> ${dbPlaceholder(2)}`,
          [finalEmail, req.params.id]
        );
        const existingEmail = existingEmailResult.rows;

        if (existingEmail.length > 0) {
          return res.status(409).json({
            success: false,
            message: 'Email/username sudah digunakan.'
          });
        }
      }
    }

    if (targetUser.peran === 'siswa') {
      const currentNis = targetUser.nis ? String(targetUser.nis).trim() : '';
      const requestedNis = nis !== undefined && nis !== null ? String(nis).trim() : '';

      if (currentNis) {
        if (requestedNis && requestedNis !== currentNis) {
          return res.status(400).json({
            success: false,
            message: 'NIS siswa yang sudah terdaftar tidak dapat diubah. Gunakan NIS yang berbeda saat membuat akun baru.'
          });
        }

        finalNis = currentNis;
      } else if (requestedNis) {
        const existingNisResult = await pool.execute(
          `SELECT id FROM users WHERE nis = ${dbPlaceholder(1)} AND peran = 'siswa' AND id <> ${dbPlaceholder(2)}`,
          [requestedNis, req.params.id]
        );
        const existingNis = existingNisResult.rows;

        if (existingNis.length > 0) {
          return res.status(409).json({
            success: false,
            message: 'NIS sudah terdaftar. Gunakan NIS yang berbeda.'
          });
        }

        finalNis = requestedNis;
      }
    }

    await pool.execute(
      `UPDATE users
       SET nama = ${dbPlaceholder(1)},
           email = ${dbPlaceholder(2)},
           mata_pelajaran = ${dbPlaceholder(3)},
           nip = ${dbPlaceholder(4)},
           kelas = ${dbPlaceholder(5)},
           nis = ${dbPlaceholder(6)}
       WHERE id = ${dbPlaceholder(7)}`,
      [String(nama).trim(), finalEmail, mata_pelajaran||null, nip||null, normalizedUserKelas, finalNis, req.params.id]
    );
    return res.json({ success: true, message: 'Profil berhasil diperbarui.' });
  } catch (err) {
    return res.status(500).json({ success: false, message: 'Terjadi kesalahan server.' });
  }
});

// ============================================================
// PATCH /api/users/:id/toggle — aktif/nonaktif (admin)
// ============================================================
router.patch('/:id/toggle', authenticate, authorize('admin'), async (req, res) => {
  try {
    const targetUser = await getUserForAccess(req.params.id);
    if (!targetUser) return res.status(404).json({ success: false, message: 'Pengguna tidak ditemukan.' });
    if (!canAccessUserTarget(req.user, targetUser, false)) return denyAccess(res);

    await pool.execute(
      `UPDATE users SET is_aktif = NOT is_aktif WHERE id = ${dbPlaceholder(1)}`,
      [req.params.id]
    );
    return res.json({ success: true, message: 'Status pengguna diperbarui.' });
  } catch (err) {
    return res.status(500).json({ success: false, message: 'Terjadi kesalahan server.' });
  }
});

async function updateManagedUserPassword(req, res) {
  const newPass = String(req.body.password || '').trim();

  if (newPass.length < 6) {
    return res.status(400).json({
      success: false,
      message: 'Password baru minimal 6 karakter.'
    });
  }

  try {
    const targetUser = await getUserForAccess(req.params.id);
    if (!targetUser) return res.status(404).json({ success: false, message: 'Pengguna tidak ditemukan.' });
    if (!canAccessUserTarget(req.user, targetUser, false)) return denyAccess(res);
    if (!['guru', 'siswa'].includes(targetUser.peran)) {
      return res.status(400).json({
        success: false,
        message: 'Password hanya dapat diedit untuk akun guru atau siswa.'
      });
    }

    const hashed = await bcrypt.hash(newPass, 10);
    await pool.execute(
      `UPDATE users SET password = ${dbPlaceholder(1)} WHERE id = ${dbPlaceholder(2)}`,
      [hashed, req.params.id]
    );

    await ensurePasswordResetRequestsTable();
    await pool.execute(
      `UPDATE password_reset_requests
       SET status = 'resolved', resolved_at = NOW()
       WHERE user_id = ${dbPlaceholder(1)} AND status = 'pending'`,
      [req.params.id]
    );

    return res.json({ success: true, message: 'Password pengguna berhasil diperbarui.' });
  } catch (err) {
    return res.status(500).json({ success: false, message: 'Terjadi kesalahan server.' });
  }
}

router.patch('/:id/password', authenticate, authorize('admin'), updateManagedUserPassword);

// ============================================================
// DELETE /api/users/:id (admin)
// ============================================================
router.delete('/:id', authenticate, authorize('admin'), async (req, res) => {
  if (req.user.id === parseInt(req.params.id)) {
    return res.status(400).json({ success: false, message: 'Tidak bisa hapus akun sendiri.' });
  }
  try {
    // Hapus file foto jika ada sebelum menghapus user
    const targetUser = await getUserForAccess(req.params.id);
    if (!targetUser) return res.status(404).json({ success: false, message: 'Pengguna tidak ditemukan.' });
    if (!canAccessUserTarget(req.user, targetUser, false)) return denyAccess(res);

    if (targetUser.foto) {
      const fotoPath = '.' + targetUser.foto;
      if (fs.existsSync(fotoPath)) {
        fs.unlinkSync(fotoPath);
      }
    }
    
    await pool.execute(
      `DELETE FROM users WHERE id = ${dbPlaceholder(1)}`,
      [req.params.id]
    );
    return res.json({ success: true, message: 'Pengguna berhasil dihapus.' });
  } catch (err) {
    return res.status(500).json({ success: false, message: 'Terjadi kesalahan server.' });
  }
});

// ============================================================
// Konfigurasi Multer untuk upload foto
// ============================================================
// Buat folder jika belum ada
const uploadDir = getUploadDir('users');

const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, uploadDir);
  },
  filename: function (req, file, cb) {
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9);
    const ext = path.extname(file.originalname);
    cb(null, `user-${req.params.id}-${uniqueSuffix}${ext}`);
  }
});

const fileFilter = (req, file, cb) => {
  const allowedTypes = /jpeg|jpg|png|gif/;
  const extname = allowedTypes.test(path.extname(file.originalname).toLowerCase());
  const mimetype = allowedTypes.test(file.mimetype);
  
  if (mimetype && extname) {
    return cb(null, true);
  } else {
    cb(new Error('Hanya file gambar yang diperbolehkan (jpeg, jpg, png, gif)'));
  }
};

const upload = multer({
  storage: storage,
  limits: { fileSize: 2 * 1024 * 1024 },
  fileFilter: fileFilter
});

// ============================================================
// POST /api/users/:id/upload-foto - upload/update foto profil
// ============================================================
router.post('/:id/upload-foto', authenticate, upload.single('foto'), async (req, res) => {
  // Cek akses: admin atau pemilik akun sendiri
  try {
    if (!req.file) {
      return res.status(400).json({ success: false, message: 'File foto tidak ditemukan.' });
    }

    // Cek apakah user ada
    const targetUser = await getUserForAccess(req.params.id);
    if (!targetUser) {
      return res.status(404).json({ success: false, message: 'Pengguna tidak ditemukan.' });
    }
    if (!canAccessUserTarget(req.user, targetUser, true)) return denyAccess(res);

    // Hapus foto lama jika ada
    if (targetUser.foto) {
      const oldFotoPath = resolveExistingPublicUploadPath(targetUser.foto);
      if (fs.existsSync(oldFotoPath)) {
        fs.unlinkSync(oldFotoPath);
      }
    }

    // Simpan path foto baru ke database
    const fotoPath = `/uploads/users/${req.file.filename}`;
    await pool.execute(
      `UPDATE users SET foto = ${dbPlaceholder(1)} WHERE id = ${dbPlaceholder(2)}`,
      [fotoPath, req.params.id]
    );

    return res.json({ 
      success: true, 
      message: 'Foto profil berhasil diupload.',
      data: { fotoUrl: fotoPath }
    });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ success: false, message: 'Terjadi kesalahan server.' });
  }
});

// ============================================================
// DELETE /api/users/:id/foto - hapus foto profil
// ============================================================
router.delete('/:id/foto', authenticate, async (req, res) => {
  // Cek akses: admin atau pemilik akun sendiri
  try {
    const targetUser = await getUserForAccess(req.params.id);
    if (!targetUser) {
      return res.status(404).json({ success: false, message: 'Pengguna tidak ditemukan.' });
    }
    if (!canAccessUserTarget(req.user, targetUser, true)) return denyAccess(res);

    if (targetUser.foto) {
      const fotoPath = resolveExistingPublicUploadPath(targetUser.foto);
      if (fs.existsSync(fotoPath)) {
        fs.unlinkSync(fotoPath);
      }
      await pool.execute(
        `UPDATE users SET foto = NULL WHERE id = ${dbPlaceholder(1)}`,
        [req.params.id]
      );
    }

    return res.json({ success: true, message: 'Foto profil berhasil dihapus.' });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ success: false, message: 'Terjadi kesalahan server.' });
  }
});

// ============================================================
// GET /api/users/:id/foto - ambil foto profil
// ============================================================
router.get('/:id/foto', authenticate, async (req, res) => {
  try {
    const targetUser = await getUserForAccess(req.params.id);
    if (!targetUser || !targetUser.foto) {
      return res.status(404).json({ success: false, message: 'Foto tidak ditemukan' });
    }
    if (!canAccessUserTarget(req.user, targetUser, true)) return denyAccess(res);
    
    const fotoPath = resolveExistingPublicUploadPath(targetUser.foto);
    if (fs.existsSync(fotoPath)) {
      res.sendFile(fotoPath);
    } else {
      res.status(404).json({ success: false, message: 'File foto tidak ditemukan' });
    }
  } catch (err) {
    res.status(500).json({ success: false, message: 'Terjadi kesalahan server' });
  }
});

module.exports = router;
