-- PostgreSQL schema for SMIASB.
-- Converted from smiasb/backend/database/smiasb_db_mysql_backup.sql.
-- This file creates schema only. It does not import data and does not change
-- the application database connection.

BEGIN;

CREATE TABLE sekolah (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_sekolah VARCHAR(150) NOT NULL,
  npsn VARCHAR(20),
  alamat TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'aktif',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sekolah_status_check CHECK (status IN ('aktif', 'nonaktif')),
  CONSTRAINT uk_sekolah_nama UNIQUE (nama_sekolah)
);

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sekolah INTEGER,
  nama VARCHAR(100) NOT NULL,
  email VARCHAR(100),
  password VARCHAR(255) NOT NULL,
  peran VARCHAR(30) NOT NULL DEFAULT 'siswa',
  mata_pelajaran VARCHAR(100),
  nip VARCHAR(30),
  kelas VARCHAR(10),
  nis VARCHAR(20),
  foto VARCHAR(255),
  is_aktif BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_peran_check CHECK (peran IN ('admin', 'super_admin', 'admin_sekolah', 'guru', 'siswa')),
  CONSTRAINT email UNIQUE (email)
);

CREATE TABLE instrumen (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sekolah INTEGER,
  judul VARCHAR(200) NOT NULL,
  deskripsi TEXT,
  jenis VARCHAR(20) NOT NULL,
  mata_pelajaran VARCHAR(100) NOT NULL,
  kelas VARCHAR(10) NOT NULL,
  jumlah_soal INTEGER NOT NULL DEFAULT 0,
  durasi_menit INTEGER NOT NULL DEFAULT 60,
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  file_path VARCHAR(255),
  file_nama VARCHAR(255),
  dibuat_oleh INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  batas_waktu TIMESTAMP,
  gunakan_batas_waktu BOOLEAN DEFAULT FALSE,
  CONSTRAINT instrumen_jenis_check CHECK (jenis IN ('HOTS', 'Literasi', 'Numerasi')),
  CONSTRAINT instrumen_status_check CHECK (status IN ('draft', 'aktif', 'nonaktif'))
);

CREATE TABLE soal (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instrumen_id INTEGER NOT NULL,
  nomor INTEGER NOT NULL,
  pertanyaan TEXT NOT NULL,
  gambar_soal VARCHAR(500),
  tabel_data TEXT,
  pilihan_a TEXT,
  pilihan_b TEXT,
  pilihan_c TEXT,
  pilihan_d TEXT,
  pilihan_e TEXT,
  jawaban_benar VARCHAR(10),
  jawaban_benar_json TEXT,
  tipe_soal VARCHAR(30) NOT NULL DEFAULT 'pilihan_ganda',
  kategori_instrumen VARCHAR(50) DEFAULT 'HOTS',
  bobot INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  pasangan_menjodohkan TEXT,
  pernyataan_checklist TEXT,
  CONSTRAINT soal_tipe_soal_check CHECK (tipe_soal IN ('pilihan_ganda', 'sebab_akibat', 'ganda_kompleks', 'benar_salah', 'menjodohkan'))
);

CREATE TABLE bank_soal (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sekolah INTEGER NOT NULL,
  source_instrumen_id INTEGER,
  source_soal_id INTEGER,
  kelas VARCHAR(10),
  mata_pelajaran VARCHAR(100),
  jenis_instrumen VARCHAR(20) NOT NULL,
  materi VARCHAR(150),
  topik VARCHAR(150),
  question_hash CHAR(64) NOT NULL,
  pertanyaan TEXT NOT NULL,
  stimulus_tambahan TEXT,
  layout_blocks TEXT,
  supporting_tables TEXT,
  media TEXT,
  gambar_soal VARCHAR(500),
  tabel_data TEXT,
  pilihan_a TEXT,
  pilihan_b TEXT,
  pilihan_c TEXT,
  pilihan_d TEXT,
  pilihan_e TEXT,
  jawaban_benar VARCHAR(10),
  jawaban_benar_json TEXT,
  tipe_soal VARCHAR(30) NOT NULL DEFAULT 'pilihan_ganda',
  kategori_instrumen VARCHAR(50),
  bobot INTEGER NOT NULL DEFAULT 1,
  pasangan_menjodohkan TEXT,
  pernyataan_checklist TEXT,
  created_by INTEGER,
  usage_count INTEGER NOT NULL DEFAULT 0,
  is_aktif BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT bank_soal_jenis_instrumen_check CHECK (jenis_instrumen IN ('HOTS', 'Literasi', 'Numerasi')),
  CONSTRAINT bank_soal_tipe_soal_check CHECK (tipe_soal IN ('pilihan_ganda', 'sebab_akibat', 'ganda_kompleks', 'benar_salah', 'menjodohkan')),
  CONSTRAINT uq_bank_soal_school_hash UNIQUE (id_sekolah, question_hash)
);

CREATE TABLE hasil (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER,
  instrumen_id INTEGER,
  skor INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hasil_siswa (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sekolah INTEGER,
  instrumen_id INTEGER NOT NULL,
  siswa_id INTEGER NOT NULL,
  nilai NUMERIC(5,2) DEFAULT 0.00,
  total_benar INTEGER DEFAULT 0,
  total_soal INTEGER DEFAULT 0,
  waktu_mulai TIMESTAMP,
  durasi_detik INTEGER,
  waktu_selesai TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_hasil UNIQUE (instrumen_id, siswa_id)
);

CREATE TABLE jawaban_siswa (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sekolah INTEGER,
  siswa_id INTEGER,
  instrumen_id INTEGER,
  soal_id INTEGER,
  jawaban TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_benar BOOLEAN DEFAULT FALSE
);

CREATE TABLE chat_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  instrumen_id INTEGER,
  pesan TEXT NOT NULL,
  balasan TEXT NOT NULL,
  is_error BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chatbot_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  normalized_prompt_hash CHAR(64) NOT NULL,
  normalized_prompt TEXT NOT NULL,
  balasan TEXT NOT NULL,
  model VARCHAR(80),
  hit_count INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  expires_at TIMESTAMP,
  last_hit_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uniq_chatbot_cache_prompt_hash UNIQUE (normalized_prompt_hash)
);

CREATE TABLE password_reset_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  identifier VARCHAR(191) NOT NULL,
  peran VARCHAR(50),
  id_sekolah BIGINT,
  status VARCHAR(30) NOT NULL DEFAULT 'pending',
  ip_address VARCHAR(80),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMP
);

CREATE TABLE password_reset_otps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  email VARCHAR(191) NOT NULL,
  otp_hash CHAR(64) NOT NULL,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  expires_at TIMESTAMP NOT NULL,
  used_at TIMESTAMP,
  ip_address VARCHAR(80),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE penugasan (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instrumen_id INTEGER NOT NULL,
  guru_id INTEGER NOT NULL,
  kelas VARCHAR(10) NOT NULL,
  tanggal_mulai TIMESTAMP NOT NULL,
  tanggal_selesai TIMESTAMP NOT NULL,
  status VARCHAR(20) DEFAULT 'aktif',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT penugasan_status_check CHECK (status IN ('aktif', 'selesai', 'batal'))
);

CREATE TABLE pengerjaan (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  penugasan_id INTEGER NOT NULL,
  siswa_id INTEGER NOT NULL,
  nilai NUMERIC(5,2),
  waktu_mulai TIMESTAMP,
  waktu_selesai TIMESTAMP,
  status VARCHAR(20) DEFAULT 'belum',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pengerjaan_status_check CHECK (status IN ('belum', 'sedang', 'selesai'))
);

CREATE TABLE activity_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER,
  aksi VARCHAR(200) NOT NULL,
  detail TEXT,
  ip_address VARCHAR(45),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_activity_log_user_id ON activity_log (user_id);

CREATE INDEX idx_bank_soal_filter ON bank_soal (id_sekolah, kelas, mata_pelajaran, jenis_instrumen, tipe_soal);
CREATE INDEX idx_bank_soal_source ON bank_soal (source_instrumen_id, source_soal_id);
CREATE INDEX idx_bank_soal_active ON bank_soal (id_sekolah, is_aktif);

CREATE INDEX idx_chatbot_cache_expires ON chatbot_cache (expires_at);
CREATE INDEX idx_chatbot_cache_last_hit ON chatbot_cache (last_hit_at);

CREATE INDEX idx_chat_history_instrumen ON chat_history (instrumen_id);
CREATE INDEX idx_chat_history_user_instrumen_created ON chat_history (user_id, instrumen_id, created_at);

CREATE INDEX idx_hasil_siswa_siswa_id ON hasil_siswa (siswa_id);

CREATE INDEX idx_instrumen_dibuat_oleh ON instrumen (dibuat_oleh);

CREATE INDEX idx_password_reset_otps_user_created ON password_reset_otps (user_id, created_at);
CREATE INDEX idx_password_reset_otps_email_created ON password_reset_otps (email, created_at);
CREATE INDEX idx_password_reset_otps_expires ON password_reset_otps (expires_at);

CREATE INDEX idx_password_reset_user_status ON password_reset_requests (user_id, status);
CREATE INDEX idx_password_reset_school_status ON password_reset_requests (id_sekolah, status);
CREATE INDEX idx_password_reset_created ON password_reset_requests (created_at);

CREATE INDEX idx_pengerjaan_penugasan_id ON pengerjaan (penugasan_id);
CREATE INDEX idx_pengerjaan_siswa_id ON pengerjaan (siswa_id);

CREATE INDEX idx_penugasan_instrumen_id ON penugasan (instrumen_id);
CREATE INDEX idx_penugasan_guru_id ON penugasan (guru_id);

CREATE INDEX idx_instrumen_tipe ON soal (instrumen_id, tipe_soal);

ALTER TABLE activity_log
  ADD CONSTRAINT activity_log_ibfk_1
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;

ALTER TABLE instrumen
  ADD CONSTRAINT instrumen_ibfk_1
  FOREIGN KEY (dibuat_oleh) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE chat_history
  ADD CONSTRAINT chat_history_ibfk_1
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  ADD CONSTRAINT fk_chat_history_instrumen
  FOREIGN KEY (instrumen_id) REFERENCES instrumen (id) ON DELETE SET NULL;

ALTER TABLE hasil_siswa
  ADD CONSTRAINT hasil_siswa_ibfk_1
  FOREIGN KEY (instrumen_id) REFERENCES instrumen (id) ON DELETE CASCADE,
  ADD CONSTRAINT hasil_siswa_ibfk_2
  FOREIGN KEY (siswa_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE penugasan
  ADD CONSTRAINT penugasan_ibfk_1
  FOREIGN KEY (instrumen_id) REFERENCES instrumen (id) ON DELETE CASCADE,
  ADD CONSTRAINT penugasan_ibfk_2
  FOREIGN KEY (guru_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE pengerjaan
  ADD CONSTRAINT pengerjaan_ibfk_1
  FOREIGN KEY (penugasan_id) REFERENCES penugasan (id) ON DELETE CASCADE,
  ADD CONSTRAINT pengerjaan_ibfk_2
  FOREIGN KEY (siswa_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE soal
  ADD CONSTRAINT soal_ibfk_1
  FOREIGN KEY (instrumen_id) REFERENCES instrumen (id) ON DELETE CASCADE;

COMMIT;

-- Run this block after importing data that contains explicit id values.
-- It resets PostgreSQL identity sequences so future inserts continue safely.
--
-- SELECT setval(pg_get_serial_sequence('activity_log', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM activity_log;
-- SELECT setval(pg_get_serial_sequence('bank_soal', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM bank_soal;
-- SELECT setval(pg_get_serial_sequence('chatbot_cache', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM chatbot_cache;
-- SELECT setval(pg_get_serial_sequence('chat_history', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM chat_history;
-- SELECT setval(pg_get_serial_sequence('hasil', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM hasil;
-- SELECT setval(pg_get_serial_sequence('hasil_siswa', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM hasil_siswa;
-- SELECT setval(pg_get_serial_sequence('instrumen', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM instrumen;
-- SELECT setval(pg_get_serial_sequence('jawaban_siswa', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM jawaban_siswa;
-- SELECT setval(pg_get_serial_sequence('password_reset_otps', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM password_reset_otps;
-- SELECT setval(pg_get_serial_sequence('password_reset_requests', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM password_reset_requests;
-- SELECT setval(pg_get_serial_sequence('pengerjaan', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM pengerjaan;
-- SELECT setval(pg_get_serial_sequence('penugasan', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM penugasan;
-- SELECT setval(pg_get_serial_sequence('sekolah', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM sekolah;
-- SELECT setval(pg_get_serial_sequence('soal', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM soal;
-- SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM users;
