-- Tahap 1 Bank Soal: tabel penyimpanan salinan soal per sekolah.
-- Aman untuk data lama: tidak mengubah tabel instrumen/soal yang sudah ada.

CREATE TABLE IF NOT EXISTS bank_soal (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_sekolah INT NOT NULL,
  source_instrumen_id INT NULL,
  source_soal_id INT NULL,
  kelas VARCHAR(10) NULL,
  mata_pelajaran VARCHAR(100) NULL,
  jenis_instrumen ENUM('HOTS','Literasi','Numerasi') NOT NULL,
  materi VARCHAR(150) NULL,
  topik VARCHAR(150) NULL,
  question_hash CHAR(64) NOT NULL,
  pertanyaan TEXT NOT NULL,
  stimulus_tambahan LONGTEXT NULL,
  layout_blocks LONGTEXT NULL,
  supporting_tables LONGTEXT NULL,
  media LONGTEXT NULL,
  gambar_soal VARCHAR(500) NULL,
  tabel_data LONGTEXT NULL,
  pilihan_a TEXT NULL,
  pilihan_b TEXT NULL,
  pilihan_c TEXT NULL,
  pilihan_d TEXT NULL,
  pilihan_e TEXT NULL,
  jawaban_benar VARCHAR(10) NULL,
  jawaban_benar_json LONGTEXT NULL,
  tipe_soal ENUM('pilihan_ganda','sebab_akibat','ganda_kompleks','benar_salah','menjodohkan') NOT NULL DEFAULT 'pilihan_ganda',
  kategori_instrumen VARCHAR(50) NULL,
  bobot INT NOT NULL DEFAULT 1,
  pasangan_menjodohkan LONGTEXT NULL,
  pernyataan_checklist LONGTEXT NULL,
  created_by INT NULL,
  usage_count INT NOT NULL DEFAULT 0,
  is_aktif TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  UNIQUE KEY uq_bank_soal_school_hash (id_sekolah, question_hash),
  INDEX idx_bank_soal_filter (id_sekolah, kelas, mata_pelajaran, jenis_instrumen, tipe_soal),
  INDEX idx_bank_soal_source (source_instrumen_id, source_soal_id),
  INDEX idx_bank_soal_active (id_sekolah, is_aktif)
);
